### ISSUE TITLE
Missing JSDoc

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/docs#102]
We write that [fetch](https://docs.opentermsarchive.org/#fetch) and [extract](https://docs.opentermsarchive.org/#extract) have a JSDoc, but we can't find any information in the [JSDoc](https://docs.opentermsarchive.org/jsdoc/) about this functions.

It's a bit strange because these functions are well commented in the code.

**Comment by MattiSG** [comment]
This issue is closed but I still can't see these functions in the [JSDoc](https://docs.opentermsarchive.org/jsdoc/).

**Comment by MattiSG** [comment]
It would be welcome to add an automated test on the generated doc to avoid this happening again in the future 🙂

**Comment by clementbiron** [comment]
There has been a [release](https://github.com/OpenTermsArchive/engine/releases/tag/v0.34.2) and the jsdoc has been generated, see [`fetch`]( https://docs.opentermsarchive.org/jsdoc/global.html#fetch).
