### ISSUE TITLE
Generate API documentation with JSDoc

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/docs#4]
The Node API of the `opentermsarchive` module should be documented in this documentation, but generated from JSDoc comments rather than written manually.

**Comment by clementbiron** [comment]
I just discovered a [GitHub action](https://github.com/andstor/jsdoc-action) to generate JSDoc and I wonder if it would not be better to generate the documentation automatically at each release of the core.

The advantage would be to not have to manually trigger the generation of the JSDoc but for the moment it is rather vague for me how one can automate the deployment of the generated doc from a GitHub action of the core repository to the `/public` folder of the docs repository. 

I would be happy to hear your opinions.

**Comment by MattiSG** [comment]
Yes, we exactly need something similar to this action, so it's great to see this is readily available 😃

I believe the most appropriate architecture is one where the logic for building and deploying is in the doc repository, as it is the one that assembles three static websites (the host website, the handwritten doc, the jsdoc); and where the engine repository triggers a build as it is the one that knows when it is appropriate to do so.
An alternative would be to let the engine build and update the underlying static files, which entails duplicating access parameters to the docs server.
