### ISSUE TITLE
Concrete Getting Started steps in the Documentation

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/docs#49]
### Problem Statement
We need to provide more concrete steps to getting started with Open Terms Archive in the documentation as this will make it easier for beginner and intermediate developers to understand it and make contributions. 

### Additional Information
_Step 1: Forked the Repo (Open Terms Archive Engine)_

_Step 2: npm install --save @opentermsarchive/engine_
![image](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/2f299506-1a72-4774-9736-96d34ec5c2bc)

_Step 3: mkdir declarations_

_Step 4: create OpenTermsArchive.json in the declarations directory_

_Step 5: npx ota-track_
![image](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/f9b09bdf-c5fe-4929-af44-4cdf32cdf923)

Got stuck in this error

### What happens if this is not addressed
Some potential contributors may be lost 

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]

Review and change the Getting started section of the docs to make it into concrete steps

**Comment by MattiSG** [comment]
Fixed in https://github.com/OpenTermsArchive/docs/pull/48 — thanks @Cli4d! 😊
