### ISSUE TITLE
Clarification to "ID" and "Service ID" references in documentation

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/docs#52]
### Problem Statement
We need to provide more clarity regarding the reference to "ID" and "Service ID" references in the documentation under contributing terms. This will help 

### Additional Information
![image](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/129b6caf-09f6-4777-b24a-5ee05bdfdb90)

![image](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/352e1320-1fe9-4a04-a66a-25de422e4ed1)

### What happens if this is not addressed
It might bring some bit of confusion among junior-level developers and they might not make up to standard contributions

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [ ] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
We can figure out if the two are referencing the same thing and if so we keep a consistent style of referencing it in the documentation

**Comment by MattiSG** [comment]
Fixed in https://github.com/OpenTermsArchive/docs/pull/48
