### ISSUE TITLE
Dead links in the documentation

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/docs#53]
### Problem Statement
We need to fix the dead link in the documentation labeled _declarations_ so that contributors can be able to follow along easily and understand the documentation

### Additional Information
![image](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/0300a7be-4853-46c7-b191-fb461bda785b)

### What happens if this is not addressed
Potential contributors might face some friction using the documentation and we might lose them or they make contributions that don't align with our standards

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
Find the exact link that should be redirected to and replace it in the documentation

**Comment by MattiSG** [comment]
Thanks @Cli4d!
It seems there are many such dead links, and we had already understood last week with @clementbiron that there is no automated tests to detect them. It should be a robot job to spot them, not a human’s!
@clementbiron do you have an easy way to add such tests? 🙂

**Comment by MattiSG** [comment]
Following https://github.com/OpenTermsArchive/docs/pull/62 and #60, all dead links have been fixed!
