### ISSUE TITLE
Naming convention issue in the docs

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/docs#54]
### Problem Statement
We need to fix a naming convention problem in the docs under the _getting started_ section so as to make the docs clear and understandable

### Additional Information
![image](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/9613a2cd-ab02-4a6d-ad16-c4aeea7d310e)

Is it meant to be **Camel casing**, or **snake casing** as stated in the contributing file here https://github.com/OpenTermsArchive/engine/blob/9c236c7f18bf4888539def7c9d80e8d0876ddf4a/CONTRIBUTING.md#L4

### What happens if this is not addressed
Different contributors might use different naming conventions and cause some confusion

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
Edit the docs and name the file properly with the required convention

**Comment by MattiSG** [comment]
As stated in the [documentation](https://docs.opentermsarchive.org/contributing-terms/#service-id), the filename is the Service ID, it may contain spaces and _should_ contain them to reflect the service name if that service is named with spaces.
In the given example, the name of the service is “Open Terms Archive” and the service ID should thus be `Open Terms Archive` 🙂 

However, I do agree that this might be misleading and that a clarification would be welcome. Could you please offer a suggestion to clarify this in the documentation? 🙂

**Comment by Cli4d** [comment]
Yeah

Let me work on something then I will open a pull request and you can review it

**Comment by MattiSG** [comment]
@Cli4d is this still relevant? 🙂

**Comment by Cli4d** [comment]
I feel it is a minor issue and we can just leave it as it is for now. If we get feedback on the same or notice contributions making the mistake, we can have a keen look at solving it. So I'll just close it for now
