### ISSUE TITLE
Typo in the contributing terms section of the documentation

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/docs#55]
### Problem Statement
We need to fix a typo in the documentation under contributing terms to make the documentation clear

### Additional Information
![image](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/93ca06fc-f669-45a9-bc49-bd41965025dd)

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
Fix the typo by replacing _and_  with a _','_

**Comment by MattiSG** [comment]
Unfortunately the screenshot is not readable anymore, making it impossible to identify the typo that should be fixed. Do you remember where it was? 🙂

**Comment by Cli4d** [comment]
Hi Matti, I think this was discussed and we realized it was ok. There was no typo as I had thought. So it's all good. I'll proceed to close this issue
