### ISSUE TITLE
Error while following the docs steps

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/docs#58]
### Problem Statement
I stumbled on some error while following the installation steps in the readme for the docs repo

### Additional Information
![image](https://github.com/OpenTermsArchive/DPG-OS-CM-Open-Terms-Archive/assets/56266330/d001bfcf-4748-4704-97f2-f9f231ec4177)

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

**Comment by MattiSG** [comment]
Fixed in https://github.com/OpenTermsArchive/docs/pull/48 — thanks @Cli4d! 😊
