### ISSUE TITLE
Install dependencies before running hugo command

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/docs#72]
The order of the terminal commands in the ReadMe need to be changed. One should first of all run `npm install` before `hugo` so that the POSTCSS dependency to be installed. 
If you run `hugo` before `npm install` you get an error

![image](https://github.com/OpenTermsArchive/docs/assets/56266330/fec77f6e-c51f-46d9-a0ff-dd01fc5fb968)

**Comment by MattiSG** [comment]
Thank you for spotting that @Cli4d!
cc @clementbiron
