### ISSUE TITLE
Rename Netlify preview subdomain

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/docs#85]
Currently, every deployment is made to a subdomain called `celebrated-scone-0489a2`. While I do like scones, is there a way to rename this to `open-terms-archive`? 😉

**Comment by clementbiron** [comment]
Yes, it's possible and easy to do. I thought it wasn't necessarily desirable.

In any case, as I've set up the preview on the `opentermsarchive.org` and `docs.opentermsarchive.org` websites, we need to choose a slug for each, for example `open-terms-archive` and `docs-open-terms-archive`.

**Comment by MattiSG** [comment]
Cool!

Could you share the reason that made you think it might not have been desirable? 🙂

I'd go with `open-terms-archive-website` and `open-terms-archive-doc`.

**Comment by clementbiron** [comment]
Done:
✅ https://open-terms-archive-website.netlify.app
✅ https://open-terms-archive-docs.netlify.app

**Comment by MattiSG** [comment]
Great, thanks @clementbiron! 😃 

After discussing with @clementbiron and @Ndpnt, our conclusion is that the duplication of this website with the Open Terms Archive official domain is not risky. If those URLs were taken into account by search engines, we would either switch to Netlify in production or set the production branch to be a dedicated branch with a `http-equiv` meta to send a `301` to `opentermsarchive.org`.
